{% set name = "dtool_lookup_server_dependency_graph_plugin" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/dtool-lookup-server-dependency-graph-plugin/dtool-lookup-server-dependency-graph-plugin-{{ version }}.tar.gz
  sha256: 4261e2708e44d7e224c53a8afa545ca6ecb28d9ba25019f3a8631a3897a90517

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools_scm
    - setuptools
  run:
    - dtool_lookup_server >=0.17.2
    - dtool_lookup_server_direct_mongo_plugin
    - dtoolcore >=3.17.0
    - python >={{ python_min }}

test:
  imports:
    - dtool_lookup_server_dependency_graph_plugin
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/IMTEK-Simulation/dtool-lookup-server-dependency-graph-plugin
  summary: dtool lookup server plugin for querying dataset dependency graphs
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
